
- name: Deploy Azure resources
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: test-ansible-rg
        location: eastus
        state: present

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: test-ansible-rg
        name: my_virtual_network
        address_prefixes: "10.0.0.0/16"
        state: present
    - name: Create network security group
      azure_rm_securitygroup:
        resource_group: test-ansible-rg
        name: my_network_security_group
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 100
        state: present

    - name: Create network interface for Ubuntu VM
      azure_rm_networkinterface:
        resource_group: test-ansible-rg
        name: my_network_interface_ubuntu
        virtual_network: my_virtual_network
        subnet: default
        state: present

    - name: Create public IP for Ubuntu VM
      azure_rm_publicipaddress:
        resource_group: test-ansible-rg
        name: my_public_ip_ubuntu
        allocation_method: Static
        state: present

    - name: Create network interface for Red Hat VM
      azure_rm_networkinterface:
        resource_group: test-ansible-rg
        name: my_network_interface_redhat
        virtual_network: my_virtual_network
        subnet: default
        state: present

    - name: Create public IP for Red Hat VM
      azure_rm_publicipaddress:
        resource_group: test-ansible-rg
        name: my_public_ip_redhat
        allocation_method: Static
        state: present

    - name: Create Ubuntu VM
      azure_rm_virtualmachine:
        resource_group: test-ansible-rg
        name: my_ubuntu_vm
        vm_size: Standard_DS1_v2
        admin_username: azureuser
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        network_interfaces:
          - name: my_network_interface_ubuntu
        os_disk:
          name: my_ubuntu_os_disk
          create_option: FromImage
          caching: ReadWrite
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 18.04-LTS
          version: latest
        state: present

    - name: Create Red Hat VM
      azure_rm_virtualmachine:
        resource_group: test-ansible-rg
        name: my_redhat_vm
        vm_size: Standard_DS1_v2
        admin_username: azureuser
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        network_interfaces:
          - name: my_network_interface_redhat
        os_disk:
          name: my_redhat_os_disk
          create_option: FromImage
          caching: ReadWrite
        image:
          offer: RHEL
          publisher: RedHat
          sku: 8.4
          version: latest
        state: present

