- name: Deploy Resource Group in Azure
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create Resource Group
      azure_rm_resourcegroup:
        name: myResourceGroup
        location: eastus
      register: rg_result

    - name: Display Resource Group Information
      debug:
        var: rg_result
