---
- name: Install Application in CentOS
  hosts: centos
  remote_user: azureuser
  become: yes
  tasks:

  - name: Read os-release file
    shell: cat /etc/os-release
    register: os_release 


  - name: Install python3-Pip
    yum:
      name: python3-pip
      state: present

  - name: Install setuptools
    yum:
      name: python3-setuptools
      state: present


  - name: Install Ansible
    pip:
      name: ansible
      state: present

  - name: Yum update
    yum:
      name: '*'
      state: latest

  - name: Install gnupg2
    yum:
      name: gnupg2
      state: present

  - name: Yum update
    yum:
      name: '*'
      state: latest 

  # - name: Install Kubectl
  #   shell: |
  #     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  #     install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

  - name: Install EPEL Repo
    yum:
      name: epel-release
      state: present

  - name: Install Yum Utils
    yum:
      name: yum-utils
      state: present

  # - name: Yum Manager
  #   shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    
  # - name: Install Python3
  #   yum:
  #     name: python3
  #     state: present

  # - name: Install pip
  #   yum:
  #     name: python3-pip
  #     state: present
      
  # - name: Install Terraform
  #   yum:
  #     name: terraform
  #     state: present

  # - name: Install Curl
  #   yum:
  #     name: curl
  #     state: present 

  # - name: Download Docker installation script
  #   get_url:
  #     url: https://get.docker.com
  #     dest: ~/get-docker.sh
  #     mode: 0755

  # - name: Run Docker installation script
  #   shell: ~/get-docker.sh

  # - name: Start Docker  
  #   service:
  #     name: docker
  #     state: started
  #     enabled: yes

  # - name: Curl Docker Compose
  #   shell: |
  #     curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

  # - name: Change Docker Compose permissions
  #   file:
  #     path: /usr/local/bin/docker-compose
  #     mode: '+x'

