- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  # - name: Include variables 
  #   include_vars: vars2.yaml
  # # - name: Include variables
  # #   include_vars:
  # #     file: vars2.yaml
  #     file: "{{ lookup('file', 'vars2.yaml') }}"
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "UbuntuAnsible-{{ item }}"
      location: "{{ item }}"
    # loop: "{{ osname }}"
    loop: ["eastus", "westus"]

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "UbuntuAnsible-{{ item }}"
      name: "{{ item }}-myVnet"
      address_prefixes: "10.0.0.0/16"
    loop: ["eastus", "westus"]

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "UbuntuAnsible-{{ item }}"
      name: "{{ item }}-mySubnet"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ item }}-myVnet"
    loop: ["eastus", "westus"]

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group:  "UbuntuAnsible-{{ item }}"
      allocation_method: Static
      name: "{{ item }}-myPublicIP"
    register: "output_ip_address"
    loop: ["eastus", "westus"]

  - name: Create Network Security Group that allows SSH   
    azure_rm_securitygroup:
      resource_group: "UbuntuAnsible-{{ item }}"
      name: "{{ item }}-myNetworkSecurityGroup"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
    loop: ["eastus", "westus"]

  - name: Create virtual network interface card       
    azure_rm_networkinterface:
      resource_group: "UbuntuAnsible-{{ item }}"
      name: "{{ item }}-myNIC"
      virtual_network: "{{ item }}-myVnet"
      subnet: "{{ item }}-mySubnet"
      public_ip_name: "{{ item }}-myPublicIP"
      security_group: "{{ item }}-myNetworkSecurityGroup"
    loop: ["eastus", "westus"]


  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "UbuntuAnsible-{{ item }}"
      name: "{{ item }}-myVM"
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      managed_disk_type: Standard_LRS
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ lookup('file', '/home/azureuser/.ssh/authorized_keys/id_rsa.pub') }}"
      network_interfaces: "{{ item }}-myNIC"
      os_type: Linux
      image:
        offer: "0001-com-ubuntu-server-jammy"
        sku: '22_04-lts-gen2'
        publisher: canonical
        version: latest
    loop: ["eastus", "westus"]
  
- name: Run az-command.sh
  hosts: localhost
  connection: local
  tasks:
    - name: Execute az-command.sh
      command: ./az-command.sh
    # - name: Create VM Image
  #   azure_rm_image:
  #     resource_group: "UbuntuAnsible-{{ item }}"
  #     name: "{{ item }}-myVMImage"
  #     source: "{{ item }}-myVM"
  #     os_type: Linux
  #     os_state: Generalized
  #     managed: true
  #   loop: ["eastus", "westus"]

  
#  os: 0001-com-ubuntu-server-jammy
#         sku: '22_04-lts-gen2'
#         publisher: canonical
#         version: latest
# loop: ["eastus", "westus"]
#loop: "["eastus", "southeastasia"]"